samples:
  metadata: "test/metadata/test_samples.tsv"
  header: False

threads: 6

outdir: "test/"
input_dir: "test/raw/"

logs: "test/logs"

import: False

trimming:
  trim: False
  adapters: "resources/adapters/NexteraPE-PE.fa"
  seedMismatches: 2
  palindromeClipThreshold: 30
  simpleClipThreshold: 10
  leading: 3
  trailing: 3
  windowSize: 4
  requiredQuality: 15
  minlength: 36

reference:
  genome: "resources/genome/C_albicans_SC5314_A21_current_chromosomes_without_mt.fasta"

