system: "linux" # or macOS

samples:
  metadata: "test/metadata/test_samples.tsv"
  header: False

threads: 8

outdir: "test/"
input_dir: "test/raw/"

logs: "test/logs"

import: False

trimming:
  trim: False
  adapters: "resources/adapters/NexteraPE-PE.fa"
  seedMismatches: 2
  palindromeClipThreshold: 30
  simpleClipThreshold: 10
  leading: 3
  trailing: 3
  windowSize: 4
  requiredQuality: 15
  minlength: 36

snp_filters:
  QD_filter: "QD < 2.0"
  FS_filter: "FS > 60.0"
  MQ_filter: "MQ < 40.0"
  SOR_filter: "SOR > 4.0"
  MQRankSum_filter: "MQRankSum < -12.5"
  ReadPosRankSum_filter: "ReadPosRankSum < -8.0"

indel_filters:
  QD_filter: "QD < 2.0"
  FS_filter: "FS > 200.0"
  SOR_filter: "SOR > 10.0"


reference:
  gff: "resources/C_albicans_SC5314_A21_current_annotations.gff"
  genome: "resources/genome/C_albicans_SC5314_A21_current_chromosomes_without_mt.fasta"
  genome_gridss: "resources/genome_gridss/C_albicans_SC5314_A21_current_chromosomes_without_mt.fasta"
